### ISSUE TITLE
document wages data

### ISSUE THREAD

**Issue by njtierney** [njtierney/brolgar#10]
* What are each of the variables in wages? 
* Is there a link to the original data?
* Can we change the variable names to be more informative?

**Comment by njtierney** [comment]
@dicook Are you able to document the `wages` data?

**Comment by dicook** [comment]
Details are section 7.9, pages 164-166

http://www.ggobi.org/book/chap-data.pdf


> On Apr 10, 2019, at 4:34 PM, Nicholas Tierney <notifications@github.com> wrote:
> 
> @dicook Are you able to document the wages data?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by njtierney** [comment]
Ah, perfect - thank you! :)

**Comment by njtierney** [comment]
@dicook it looks like the following variables are tranformations of `hgc` and `uerate` - do we want to keep these? Or should I get rid of them.

```
hgc.9
ue.7
ue.centert1
ue.mean
ue.person.cen
ue1
```

**Comment by dicook** [comment]
Yes, it would be less confusing without them. I just used the data distributed from the book referenced
