### ISSUE TITLE
devtools::check() fails because wages_ts data is not up to date

### ISSUE THREAD

**Issue by njtierney** [njtierney/brolgar#46]
Current status of the names in brolgar:

``` r
library(brolgar)
names(wages)
#> [1] "id"       "lnw"      "exper"    "ged"      "postexp"  "black"   
#> [7] "hispanic" "hgc"      "uerate"
names(wages_ts)
#> [1] "id"            "ln_wages"      "xp"            "ged"          
#> [5] "postexp"       "black"         "hispanic"      "high_grade"   
#> [9] "unemploy_rate"
packageVersion("brolgar")
#> [1] '0.0.2.9000'
```

<sup>Created on 2019-07-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

But when I run this code in a chunk in a vignette:

```{r}
is_xp_in_wages <- "xp" %in% names(wages_ts)

if (!is_xp_in_wages){
  stop("xp isn't in names of wages_ts?", 
       glue::glue_collapse(names(wages_ts), sep = ", ", last = ", and "),
       glue::glue_collapse(class(wages_ts), sep = ", "))
}
```

I get this error:

```
E  creating vignettes (13.9s)
   Quitting from lines 37-44 (visualisation-gallery.Rmd) 
   Error: processing vignette 'visualisation-gallery.Rmd' failed with diagnostics:
   xp isn't in names of wages_ts?id, lnw, exper, ged, postexp, black, hispanic, hgc, and ueratetbl_ts, tbl_df, tbl, data.frame
   Execution halted
```

I cannot work out how to fix this!

**Comment by njtierney** [comment]
I get this error repeated in travis https://travis-ci.org/njtierney/brolgar/jobs/558444441#L4179.

Going to update to R 3.6.1 to see if that fixes it.

**Comment by dicook** [comment]
I have been getting errors when dependent packages are not explicitly loaded. It’s not comprehensive, just the occasional package and the error is similar. It looks like a package called xp?

**Comment by njtierney** [comment]
the name `xp` is a new name that I have the `exper` column - for some reason it hasn't saved the name name...

**Comment by njtierney** [comment]
Fixed in https://github.com/njtierney/brolgar/commit/0a80d63b82776251396605dcf6d1a721e82ee816
