### ISSUE TITLE
Broglar not installing in R version 3.5.0 

### ISSUE THREAD

**Issue by osoroe** [njtierney/brolgar#67]
Below is the message i get when trying to install broglar. Is there anything i need to do to install the package

install.packages("broglar")
Installing package into ‘C:/Users/Eric/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘broglar’ is not available (for R version 3.5.0)

**Comment by njtierney** [comment]
Thanks for posting an issue here - `brolgar` is not currently available on CRAN, to install it see the guide here: https://github.com/njtierney/brolgar#installation

`
