### ISSUE TITLE
feat_five_num returns tibble of lists

### ISSUE THREAD

**Issue by njtierney** [njtierney/brolgar#99]
library(brolgar)

    heights %>%
      features(height_cm, list(min = min))
    #> # A tibble: 144 x 2
    #>    country       min
    #>    <chr>       <dbl>
    #>  1 Afghanistan  161.
    #>  2 Albania      168.
    #>  3 Algeria      166.
    #>  4 Angola       159.
    #>  5 Argentina    167.
    #>  6 Armenia      164.
    #>  7 Australia    170 
    #>  8 Austria      162.
    #>  9 Azerbaijan   170.
    #> 10 Bahrain      161.
    #> # … with 134 more rows

    heights %>%
      features(height_cm, feat_ranges)
    #> # A tibble: 144 x 5
    #>    country       min   max range_diff   iqr
    #>    <chr>       <dbl> <dbl>      <dbl> <dbl>
    #>  1 Afghanistan  161.  168.       7     3.27
    #>  2 Albania      168.  170.       2.20  1.53
    #>  3 Algeria      166.  171.       5.06  2.15
    #>  4 Angola       159.  169.      10.5   7.87
    #>  5 Argentina    167.  174.       7     2.21
    #>  6 Armenia      164.  172.       8.82  5.30
    #>  7 Australia    170   178.       8.4   2.58
    #>  8 Austria      162.  179.      17.2   5.35
    #>  9 Azerbaijan   170.  172.       1.97  1.12
    #> 10 Bahrain      161.  164        3.3   2.75
    #> # … with 134 more rows

    # returns lists instead of numbers
    heights %>%
      features(height_cm, feat_five_num)
    #> # A tibble: 144 x 6
    #>    country     min       q25       med       q75       max      
    #>    <chr>       <list>    <list>    <list>    <list>    <list>   
    #>  1 Afghanistan <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  2 Albania     <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  3 Algeria     <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  4 Angola      <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  5 Argentina   <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  6 Armenia     <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  7 Australia   <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  8 Austria     <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #>  9 Azerbaijan  <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #> 10 Bahrain     <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]> <dbl [1]>
    #> # … with 134 more rows

<sup>Created on 2020-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidski** [comment]
Looking at https://github.com/njtierney/brolgar/blob/master/R/features.R#L38-L46, replacing the `list()` construct with a `c()` version seems to correct this behavior.

```r
feat_five_num2 <- function (x, ...)  {
    c(min = b_min(x, ...), q25 = b_q25(x, ...), med = b_median(x, 
        ...), q75 = b_q75(x, ...), max = b_max(x, ...))
}
```

**Comment by njtierney** [comment]
Thank you!
